### PR TITLE
Make resource creation more exact and testable

### PR DESCRIPTION
**Pull request by RubenVerborgh**
I found the language to be inaccurate (`PUT and PATCH requests`), but also not testable.
There is no way to test the desires of a client; but we can test the behavior of the server.
So, in my opinion, it's the server that `MUST`, not the client.

### CODE REVIEW

**Review by csarven — CHANGES_REQUESTED** [review]
I think mention of client can be omitted altogether. Also focus on effective request URI.

Changing the requirement's focus (from clients) to servers is perhaps most useful for PATCH because it changes resource creation from MAY (RFC5789) to MUST. For PUT and POST, the requirement is actually not needed because it is already covered by RFC 7231.

**Comment by RubenVerborgh** [comment]
@csarven Agree with all.

**Comment by csarven** [comment]
Should we still guide (informative/note) the clients along the lines of:

Clients can use PUT and PATCH requests to assign a URI to a resource. Clients can use POST requests to have the server assign a URI to a resource.

**Comment by csarven** [comment]
Added commit. Have a look. Interesting that GitHub doesn't allow me to request a review from you (sort of obviously).

**Comment by RubenVerborgh** [comment]
Thanks, @csarven. Approved!

**Review by csarven — APPROVED** [review]

**Pull request merged**
