### PR TITLE
Add 2023-09-11 agenda and minutes

### PR DESCRIPTION
**Pull request by csarven**
Request to merge in 24 hours following meeting.

---

[Preview](https://github.com/solid/specification/blob/a055f54ac6ee848582d91b3eb064253870cd2753/meetings/2023-09-11.md)

### CODE REVIEW

**Comment by woutermont** [comment]
@laurensdeb, could you add the name/initials of the person who asked the questions at the end? Thanks!

**Comment by laurensdeb** [comment]
@woutermont I don't have the appropriate rights to modify the PR. The person asking the questions towards the end of the last agenda topic was Mirja Kühlewind (Ericsson). I believe their name is also incorrect in the list of attendees.

**Comment by csarven** [comment]
Is Mia listed under Present supposed to be Mirja?

**Comment by csarven** [comment]
Thanks, updated. FYI, GitHub has a feature in the UI to make change suggestions on PRs.

**Pull request merged**
