### PR TITLE
Clarify server advertising storage resource with Link relation

### PR DESCRIPTION
**Pull request by csarven**
This PR includes "Corrections that do not add new features" ( https://www.w3.org/2021/Process-20211102/#class-3 ), in particular:

>clears up an ambiguity or under-specified part of the specification in such a way that data, a processor, or an agent whose conformance was once unclear becomes clearly either conforming or non-conforming.

If this behaviour is in conflict with people's interpretation of the specification and implementation, please do chime in.

Closes https://github.com/solid/specification/issues/484

### CODE REVIEW

**Review by matthieubosquet — APPROVED** [review]
I love this clarification.

**Review by kjetilk — APPROVED** [review]
Indeed and improvement.

**Review by acoburn — APPROVED** [review]

**Review by justinwb — APPROVED** [review]
✅ ✅

**Comment by csarven** [comment]
@RubenVerborgh , I'd like your review.

**Review by RubenVerborgh — APPROVED** [review]
Looks good to me, but will invite @joachimvh to cross-check this with the CSS implementation.

**Pull request merged**
