### PR TITLE
Add W3C Solid CG weekly meeting to Participation

### PR DESCRIPTION
**Pull request by csarven**
This is a proposal to have a weekly meeting for the W3C Solid Community Group (CG) as mentioned in the solid/specification Gitter chat [1] and in the W3C TPAC 2022 meeting [2].

There is an event that's drafted [3] - scheduled for Wednesdays at 14:00 UTC - for the CG calendar [4]. We will not observe daylight savings time.

Anyone may join the meeting. Participants must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct (CEPC) [5].

The Chair will propose and approve the agenda for each meeting. Participants are welcome to review and propose agenda topics.

The Solid Technical Reports Contributing Guide [6] describes different ways to contribute and follow the Solid project.

The CG Meeting Guidelines [7] describes how to participate and record meetings.

There is a minutes template [8] that can be used by scribes to transcribe the meeting.

As it stands, the CG weekly call is not intended to replace the panel meetings. Panel meetings can continue to further the development of their Work Items [9].

Bear in mind that the proposed time [3] worked reasonably well in the past for the (occasional) CG-wide meetings but unfortunately overlaps with one of the panel meetings.

Considering the current state of panels [1][2], we can revisit how Solid Panels work as per the Solid process [10]. Alternatively, Task Forces can be formed to carry out specific assignments for the CG [11], e.g., documentation similar to Panel Charters ([12][13]) but with smaller scope. Solid Panels and W3C Group Task Forces are general similar but we will need to fine tune this going forward.

[1] https://gitter.im/solid/specification?at=632c64a772ad51741ff272a3
[2] https://github.com/solid/specification/blob/main/meetings/2022-09-14.md#panels
[3] https://www.w3.org/events/meetings/0caa6ba5-5523-4e16-b514-aeec098e4d72/20221005T140000
[4] https://www.w3.org/groups/cg/solid/calendar
[5] https://www.w3.org/Consortium/cepc/
[6] https://github.com/solid/specification/blob/main/CONTRIBUTING.md
[7] https://github.com/solid/specification/blob/main/meetings/README.md
[8] https://github.com/solid/specification/blob/main/meetings/template.md
[9] https://solidproject.org/TR/
[10] https://github.com/solid/process/blob/main/README.md#solid-panels
[11] https://www.w3.org/2021/Process-20211102/#ReqsAllGroups
[12] https://github.com/solid/process/blob/main/test-suite-panel-charter.md
[13] https://github.com/solid/process/blob/main/notifications-panel-charter.md

### CODE REVIEW

**Review by VirginiaBalseiro — APPROVED** [review]

**Review by acoburn — APPROVED** [review]
This is a very good idea

**Comment by TallTed** [comment]
+100!

I encourage you to take this event out of DRAFT as soon as reasonable, as the DRAFT event will not show up on subscriber calendars (like mine), so conflicting events may be created.

I also support the general idea of transforming Panels into Task Forces, with whatever tweaks to the boilerplate TF Charter are needed to let the CG Panels continue to operate mostly as they have been.  If we need to massage the operation of the Panels a bit, that's probably OK, too.

Whether or not the Solid Panels become CG TFs, I encourage adding their meeting times to the Solid CG calendar with appropriate naming and such, so that any existing conflicts are revealed and future conflicts may be minimized if not avoided entirely.

**Review by elf-pavlik — APPROVED** [review]
In a couple of weeks, this will be 8AM for me (UTC-06:00) but it's ok.
I guess we do not anticipate participation from NA Pacific TIme (UTC-08:00) since this will be 6AM there.

**Comment by elf-pavlik** [comment]
FYI I also shared this issue on the *Solid Contributors* Slack https://app.slack.com/client/TULFFSKC2/CV1FDJWEA

There was a very recent conversation there that included the topic of panels and meetings.

**Comment by elf-pavlik** [comment]
> There is an event that's drafted [3] - scheduled for Wednesdays at 14:00 UTC - for the CG calendar [4]. We will not observe daylight savings time.

Will the meeting start today?

**Comment by csarven** [comment]
Thanks all!

I observe no objections. I suggest that we accept this proposal until there is a general decision to update the parameters of the weekly meeting. The following is from the meeting guidelines applies and all feedback is very welcome!

>Operating principle for effective participation is to allow access across disabilities, across country borders, and across time. Feedback on tooling and meeting timing is welcome.

The next meeting will be on 2022-10-12 at 14:00 UTC. 
I'm looking forward to it!

See the CG calendar for event updates: https://www.w3.org/events/meetings/0caa6ba5-5523-4e16-b514-aeec098e4d72 as well as the README in this repository for other information.

**Pull request merged**
