### PR TITLE
Add protect-sensitive-information advisement

### PR DESCRIPTION
**Pull request by csarven**
[Correction class 2 change](https://www.w3.org/2023/Process-20231103/#class-2) that advises servers to take additional measures to protect sensitive information in identity documents.

---

[Preview](http://htmlpreview.github.io/?https://github.com/solid/specification/blob/f8bdeec8f6492b043b40bf0bbdae49509cd084b5/ED/protocol.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F13d48de6a3e61695cda36cb0b12d672b90e2376d%2FED%2Fprotocol.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Ff8bdeec8f6492b043b40bf0bbdae49509cd084b5%2FED%2Fprotocol.html)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
Does it intend to address any specific open issue?

**Review by VirginiaBalseiro — APPROVED** [review]

**Comment by csarven** [comment]
This is a non-normative general advisement based on community discussions that encourage common security practices.

**Comment by elf-pavlik** [comment]
I assume *Servers* refers specifically to the instances of the product class *Server* defined in https://solidproject.org/ED/protocol#classes-of-products

**Review by elf-pavlik — APPROVED** [review]
I'm not sure how actionable this consideration is. Maybe one day we can gather feedback showing what actions various implementations have taken based on this specific consideraton.

**Pull request merged**
